### ISSUE TITLE
homework2

### ISSUE THREAD

**Issue by Taniann** [volodymyrtaras/HomeworkMA#1]
- [TaskOne.java#L4](https://github.com/volodymyrtaras/HomeworkMA/blob/dcf6c321383b4e560870634f1bfb4c050ffe2d27/src/lesson/two/TaskOne.java#L4) redundant blank line. [ A blank line before the first member or initializer, or after the last member or initializer of the class, is neither encouraged nor discouraged.](https://mate-academy.github.io/style-guides/java/java.html#s4.6.1-vertical-whitespace)
- use more meaningful class names. describe what classes do instead of of number of task is it (!) 
- [TaskOne.java#L3](https://github.com/volodymyrtaras/HomeworkMA/blob/dcf6c321383b4e560870634f1bfb4c050ffe2d27/src/lesson/two/TaskOne.java#L3) change name => Group or smth like that. And it is not the best implementation of builder pattern. Try to invoke `        System.out.println("Checking the attendance of students...");

        TaskOne lesson = new TaskOne.Builder()
                .withStudentOne("Andriy Kulynych")
                .withStudentTwo("Victor Makarov")
                .withStudentThree("Slava Cheban")
                .withStudentFour("Dima Romanutskyi")
                .withStudentFive("Ihor Mustiatsa")
                .build();

        String list = (lesson.studentOne + ", "
                + lesson.studentTwo + ", "
                + lesson.studentThree + ", "
                + lesson.studentFour + ", "
                + lesson.studentFive);

        System.out.println(list);`
in another class (for example BuilderApp) what will you have? (!)

- it is not necessarily return int[] because you didnt create a copy of array, you work directly with passed array
- why dont you invoke created sort methods here (!)
- [redundant blank line]((https://github.com/volodymyrtaras/HomeworkMA/blob/dcf6c321383b4e560870634f1bfb4c050ffe2d27/src/lesson/two/TaskFour.java#L8) [and here](https://github.com/volodymyrtaras/HomeworkMA/blob/dcf6c321383b4e560870634f1bfb4c050ffe2d27/src/lesson/two/TaskFour.java#L13)
- [TaskFour.java#L7](https://github.com/volodymyrtaras/HomeworkMA/blob/dcf6c321383b4e560870634f1bfb4c050ffe2d27/src/lesson/two/TaskFour.java#L7) => `    public TaskFour(int someValue) {
        this.someValue = someValue;
    }`
change it (!)

RESULT: be sure to correct all comments marked by (!) to get your hw accepted. google implementation of builder and change it to better version.

**Comment by Taniann** [comment]
- [Questionnaire.java#L58)](https://github.com/volodymyrtaras/HomeworkMA/blob/777f45ef1e603c95e565226e78223a963454f520/src/lesson/two/Questionnaire.java#L58) it is not a good practice to get directly information from fields. use getters. now you can not get fields info from your Questionnaire in another class
- [Immutable.java#L9](https://github.com/volodymyrtaras/HomeworkMA/blob/777f45ef1e603c95e565226e78223a963454f520/src/lesson/two/Immutable.java#L9) better to pass value as constructor param

be sure to correct these comments to get your hw accepted

**Comment by Taniann** [comment]
- [Immutable.java#L9](https://github.com/volodymyrtaras/HomeworkMA/blob/5b8ca486842e3f6bc35150942e4686cf03ab40b8/src/lesson/two/Immutable.java#L9) this.someValue = someValue is standart constructor statement
- class Questionnaire move getters before class Builder

be sure to correct, but for now I accept hw

**Comment by volodymyrtaras** [comment]
> * [Immutable.java#L9](https://github.com/volodymyrtaras/HomeworkMA/blob/5b8ca486842e3f6bc35150942e4686cf03ab40b8/src/lesson/two/Immutable.java#L9)  `this.someValue = someValue` is standart constructor statement
> * class Questionnaire move getters before class Builder
> 
> be sure to correct, but for now I accept hw

fixed
